# Generated by Django 5.1.7 on 2025-03-28 01:20

import atencion.models
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('atencion', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelManagers(
            name='usuario',
            managers=[
                ('objects', atencion.models.CustomUserManager()),
            ],
        ),
    ]
